FROM caddy:builder AS builder

RUN xcaddy build{% if caddy_use_cloudflare_dns_challenge %} \
    --with github.com/caddy-dns/cloudflare{% endif %}

FROM caddy:2

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
