---
- name: Setup Jellyfin
  hosts: deploy
  vars_files:
    - "{{ playbook_dir }}/../vars/host_secrets.yml"
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
    docker_user: "{{ username }}"
  roles:
    - role: ensure_directory
      vars:
        path: /srv/docker/
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 755
        recurse: true

    - role: docker_network
      vars:
        docker_network_name: glendza_home_server

    - role: jellyfin
      vars:
        docker_user: "{{ username }}"
        docker_group: "{{ username }}"
        docker_network: glendza_home_server
        jellyfin_image_tag: latest
        jellyfin_service_directory: /srv/docker/services/jellyfin
        jellyfin_volumes_directory: /srv/docker/volumes/jellyfin
        jellyfin_media_directory: /mnt/jellyfin_data/media
